# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colima HackLab
email: contacto@hackLab.cc
description: > # this means to ignore newlines until "baseurl:"
  "Laboratorio aut贸nomo de experimentaci贸n, producci贸n colaborativa e innovaci贸n"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hacklab.cc" # the base hostname & protocol for your site
twitter_username: colimahacklab
github_username:  colimahacklab

# Build settings
markdown: kramdown
